### ISSUE TITLE
It seems that there are issues with the newest ULib hook implementation

### ISSUE THREAD

**Issue by CSchulz** [oubliette32/DBugR#7]
[ERROR] addons/dbugr/lua/dbugr/core/perfmon/sh_perfmon_hook.lua:56: attempt to index local 'oldHooks' (a nil value)
1. unknown - addons/dbugr/lua/dbugr/core/perfmon/sh_perfmon_hook.lua:56

Timer Failed! [Simple][@addons/dbugr/lua/dbugr/core/perfmon/sh_perfmon_hook.lua (line 134)]

**Comment by chadreed93** [comment]
I also have this issue

**Comment by OnlyNoob** [comment]
Change:
local _, oldHooks = debug.getupvalue(DBugR.Profilers.Hook.OldHA, 3);
To:
local _, oldHooks = debug.getupvalue(DBugR.Profilers.Hook.OldHA, 4);
